### ISSUE TITLE
great work!

### ISSUE THREAD

**Issue by Marcophono2** [pharmapsychotic/clip-interrogator#15]
Really fascinating! And in some cases I could "reproduce" nearly exactly the image from the prompt in Stable Diffusion. Wow!!
Just two questions I am interested in from the technical view:

1. Why can it happen that the prompt from the same image can be different when restarting the process? Does the code start with a random noise, but here on the token embedding side?
2. Where are the differences between fast and best mode? The fast mode let me process the image in less than 0.1 seconds. The best mode takes 8 seconds. The result of the best mode is better but not 80 times better. ;) I would say "a bit" better. The classic mode on the other side outputed a rather bad result. To be honest my statistical material is restricted to my very last prompt generation. ;) But even if more tests would come to different results my questions would still not be answered.

Best regards
Marc

P.S: I am on cuda, RTX 4090

**Comment by pharmapsychotic** [comment]
thanks!!

1. hmm i hadn't noticed that yet. i think it should be deterministic and i've seen same prompts from same images in my testing. of course between updates to the code things can change. i'll have to keep an eye out for this!
2. the "best" mode progressively adds more flavors to the prompt moving it closer and closer to alignment with the image. this requires computing thousands of text embeddings at each step. the "fast" mode skips all this and just strings together the top flavors in one go and is able to use all the precomputed embeddings. i've got big list of ideas on how to make faster version of best so expect that to speed up or new preset between fast and best to arrive :)

**Comment by Marcophono2** [comment]
@pharmapsychotic Wonderful! I really love your work! Surely funny for you to hear that but I could impress some friends yesterday with YOUR work! :-D

**Comment by Marcophono2** [comment]
@pharmapsychotic But indeed, I have the same question which was already asked here: Isn't it possible to increase the value for the amount of exported tokens? I know that there is that 77 token limit for SD but I am just interested in that what would also be outputed. If I increase the value from 32 to 64 or else, nothing changed. On the other hand side, when I decrease it to i.E. 4, then only 5 phrases are outputed. So, where is the code which decided "That's enough! I stop that crazy guy here!"  ?

`tops = merged.rank(image_features, 32)`

**Comment by pharmapsychotic** [comment]
so for the `interrogate_fast` the stopping happens at https://github.com/pharmapsychotic/clip-interrogator/blob/main/clip_interrogator/clip_interrogator.py#L136 with the call to `_truncate_to_fit` 
in the implementation https://github.com/pharmapsychotic/clip-interrogator/blob/main/clip_interrogator/clip_interrogator.py#L296 it attempts to tokenize the prompt and if it fails repeatedly removes the last flavor until it fits. it could remove just the final characters until it fits instead of whole flavor phrase but that could change the meaning and worsen alignment. I haven't done a full test to see if having partial final flavor would overall help or hurt but my thought was better for it not to truncate within flavor text so it remains readable to the user.

**Comment by Marcophono2** [comment]
Hello @pharmapsychotic ! Sorry to be such a pain. :-)
I tried to find out why AUTOMATIC1111 outputs other results with its interrogator than your script. Obviously 1111 uses another model. 
Yours is https://storage.googleapis.com/sfr-vision-language-research/BLIP/models/model_large_caption.pth
1111 uses https://storage.googleapis.com/sfr-vision-language-research/BLIP/models/model_base_caption_capfilt_large.pth

I then tried just to replace the link in your file clip_interrogator.py but that didn't work. I get
```
Loading BLIP model...
load checkpoint from https://storage.googleapis.com/sfr-vision-language-research/BLIP/models/model_base_caption_capfilt_large.pth
Traceback (most recent call last):
  File "/home/marc/Schreibtisch/AI/clip/eulerclippi.py", line 25, in <module>
    ci = Interrogator(config)
  File "/home/anaconda3/envs/EulerClip/lib/python3.10/site-packages/clip_interrogator/clip_interrogator.py", line 54, in __init__
    blip_model = blip_decoder(
  File "/home/marc/Schreibtisch/AI/src/blip/models/blip.py", line 176, in blip_decoder
    assert(len(msg.missing_keys)==0)
AssertionError
```

This is the corresponding file of 1111:

https://github.com/AUTOMATIC1111/stable-diffusion-webui/blob/master/modules/interrogate.py

Can you help me to bring your script to run with that other model? For my tests it outputs better results.

**Comment by Marcophono2** [comment]
@pharmapsychotic Okay, I just rebuild the code from https://github.com/salesforce/BLIP . But what 1111 has is an artist list which really makes sense for my tests but I don't know how this one is processed. It seems that 1111 does not have to calculate the rank for every singe artist. At least it is rather quick. Or am I wrong?
https://github.com/AUTOMATIC1111/stable-diffusion-webui/blob/master/modules/interrogate.py#L157

**Comment by pharmapsychotic** [comment]
umm looks like they changed to have option to look at different list of artists. I could put in a way to override the default tables with custom data. I'll think how to best include that in the API. hmm maybe just paths in the Config 🤔
