### ISSUE TITLE
New instructions to get running local? 

### ISSUE THREAD

**Issue by screan** [pharmapsychotic/clip-interrogator#21]
HI, I had this running local fine, but just updated and broke it. Is there new process? 

```
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
~\AppData\Local\Temp\ipykernel_17848\3198441247.py in <module>
     34 os.makedirs('cache', exist_ok=True)
     35 for url in CACHE_URLS:
---> 36     print(subprocess.run(['wget', url, '-P', 'cache'], stdout=subprocess.PIPE).stdout.decode('utf-8'))
     37 
     38 

Anaconda3\lib\subprocess.py in run(input, capture_output, timeout, check, *popenargs, **kwargs)
    503         kwargs['stderr'] = PIPE
    504 
--> 505     with Popen(*popenargs, **kwargs) as process:
    506         try:
    507             stdout, stderr = process.communicate(input, timeout=timeout)

Anaconda3\lib\subprocess.py in __init__(self, args, bufsize, executable, stdin, stdout, stderr, preexec_fn, close_fds, shell, cwd, env, universal_newlines, startupinfo, creationflags, restore_signals, start_new_session, pass_fds, user, group, extra_groups, encoding, errors, text, umask)
    949                             encoding=encoding, errors=errors)
    950 
--> 951             self._execute_child(args, executable, preexec_fn, close_fds,
    952                                 pass_fds, cwd, env,
    953                                 startupinfo, creationflags, shell,

Anaconda3\lib\subprocess.py in _execute_child(self, args, executable, preexec_fn, close_fds, pass_fds, cwd, env, startupinfo, creationflags, shell, p2cread, p2cwrite, c2pread, c2pwrite, errread, errwrite, unused_restore_signals, unused_gid, unused_gids, unused_uid, unused_umask, unused_start_new_session)
   1418             # Start the process
...
-> 1420                 hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
   1421                                          # no special security
   1422                                          None, None,

FileNotFoundError: [WinError 2] The system cannot find the file specified
```

**Comment by screan** [comment]
thanks!, @pharmapsychotic getting this now
```
Loading CLIP model...
Preprocessing artists:   0%|                                                                                         | 0/5 [00:01<?, ?it/s]
Traceback (most recent call last):
  File "\clip-interrogator\run_gradio.py", line 11, in <module>
    ci = Interrogator(Config(cache_path="cache", clip_model_path="cache"))
  File "\clip-interrogator\clip_interrogator\clip_interrogator.py", line 70, in __init__
    self.load_clip_model()
  File "\clip-interrogator\clip_interrogator\clip_interrogator.py", line 105, in load_clip_model
    self.artists = LabelTable(artists, "artists", self.clip_model, self.tokenize, config)
  File "\clip-interrogator\clip_interrogator\clip_interrogator.py", line 268, in __init__
    text_features = clip_model.encode_text(text_tokens)
  File "AppData\Local\Programs\Python\Python310\lib\site-packages\open_clip\model.py", line 192, in encode_text
    x = self.transformer(x, attn_mask=self.attn_mask)
  File "\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\nn\modules\module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "AppData\Local\Programs\Python\Python310\lib\site-packages\open_clip\transformer.py", line 230, in forward
    x = r(x, attn_mask=attn_mask)
  File "AppData\Local\Programs\Python\Python310\lib\site-packages\torch\nn\modules\module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "AppData\Local\Programs\Python\Python310\lib\site-packages\open_clip\transformer.py", line 154, in forward
    x = x + self.ls_1(self.attention(self.ln_1(x), attn_mask=attn_mask))
  File "AppData\Local\Programs\Python\Python310\lib\site-packages\torch\nn\modules\module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "AppData\Local\Programs\Python\Python310\lib\site-packages\open_clip\transformer.py", line 18, in forward
    x = F.layer_norm(x.to(torch.float32), self.normalized_shape, self.weight, self.bias, self.eps)
  File "\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\nn\functional.py", line 2515, in layer_norm
    return torch.layer_norm(input, normalized_shape, weight, bias, eps, torch.backends.cudnn.enabled)
RuntimeError: expected scalar type Float but found Half
```

**Comment by pharmapsychotic** [comment]
thanks, in a fresh environment I get that too but not in my other environments 🤔 it may be difference in behavior with different torch version, I'm investigating!

**Comment by pharmapsychotic** [comment]
ah! it happens when run in "cpu" mode. if you do have gpu make sure to run
`pip3 install --upgrade torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cu117` to get a version of torch that supports GPU. 
I'll update README and add handling for CPU so it doesn't die from using half's

**Comment by pharmapsychotic** [comment]
ok instructions updated and version 0.3.1 that handles running on CPU again published!

**Comment by screan** [comment]
> ah! it happens when run in "cpu" mode. if you do have gpu make sure to run `pip3 install --upgrade torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cu117` to get a version of torch that supports GPU. I'll update README and add handling for CPU so it doesn't die from using half's

YES, thank you this fixed it. Weird I have  a 3090..

**Comment by johnclendenen** [comment]
> ok instructions updated and version 0.3.1 that handles running on CPU again published!

Was this pushed? I don't see any CPU specific instructions in the README and I'm still hitting the float/half error.

**Comment by screan** [comment]
@pharmapsychotic Getting an error now that GPU is not available with last update. Is there a way to not use CPU? 

`CUDA is not available, using CPU. Warning: this will be very slow!`

**Comment by pharmapsychotic** [comment]
@screan check to make sure your installed torch has cuda enabled
```
python
import torch
torch.cuda.is_available()
```

**Comment by screan** [comment]
@pharmapsychotic thanks reinstalled cuda tools / pytorch. all working now. appreciate it.
