### ISSUE TITLE
'charmap' codec can't encode character '\U0001f380'

### ISSUE THREAD

**Issue by geocine** [pharmapsychotic/clip-interrogator#38]
I don't know exactly where did this come from but here is the error I got:

```sh
Traceback (most recent call last):
  File "E:\AIML\data\jisoo-data\caption.py", line 17, in <module>
    f.write(output)
  File "C:\Users\Aivan\miniconda3\envs\st\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\U0001f380' in position 105: character maps to <undefined>
```

code:
```python
import os
from PIL import Image
from clip_interrogator import Config, Interrogator

folder_path = "/path/to/input"
output_folder = "/path/to/output"
ci = Interrogator(Config(clip_model_name="ViT-L-14/openai"))

for image_name in os.listdir(folder_path):
    if image_name.endswith(".png"):
        image_path = os.path.join(folder_path, image_name)
        image = Image.open(image_path).convert('RGB')
        output = ci.interrogate(image)
        output_path = os.path.splitext(image_name)[0] + ".txt"
        output_path = os.path.join(output_folder, output_path)
        with open(output_path, "w") as f:
            f.write(output)
```

Here is my image directory for reproduction:
[images.zip](https://github.com/pharmapsychotic/clip-interrogator/files/10521204/images.zip)

Archive Info:
https://www.virustotal.com/gui/url/896f6836c6d5e0c8bd61b549c258bc9ba672e03a56ede1a4c95098a1938b819b/detection

**Comment by pharmapsychotic** [comment]
Try opening your txt files with 
```
with open(output_path, 'w', encoding='utf-8')
```
That way it should be able to output unicode characters without problem

**Comment by geocine** [comment]
Oops sorry , I really appreciate your even replying in this mistake. Thanks again!
