### ISSUE TITLE
AttributeError: module 'torch.backends' has no attribute 'mps'

### ISSUE THREAD

**Issue by nailz420** [pharmapsychotic/clip-interrogator#50]
Fatal error on start:

Traceback (most recent call last):
  File "F:\projects\AI\CLIP-Interrogator\run_cli.py", line 9, in <module>
    from clip_interrogator import Interrogator, Config
  File "d:\Users\nailz\anaconda3\lib\site-packages\clip_interrogator\__init__.py", line 1, in <module>
    from .clip_interrogator import Interrogator, Config
  File "d:\Users\nailz\anaconda3\lib\site-packages\clip_interrogator\clip_interrogator.py", line 43, in <module>
    class Config:
  File "d:\Users\nailz\anaconda3\lib\site-packages\clip_interrogator\clip_interrogator.py", line 65, in Config
    device: str = ("mps" if torch.backends.mps.is_available() else "cuda" if torch.cuda.is_available() else "cpu")
AttributeError: module 'torch.backends' has no attribute 'mps'

Windows 11 intel x64, python 3.10.7 or conda with 3.9

**Comment by victorca25** [comment]
Maybe upgrade PyTorch? The MPS backend was not added that long ago, since you have Windows from the error at least it seems to be and old version of PyTorch without the MPS backend: https://pytorch.org/docs/stable/notes/mps.html

**Comment by nailz420** [comment]
The problem seems to be environment configuration related. Torch uninstall and re-install seems to have updated torch to the correct version.

Thanks,
Tim.
