### ISSUE TITLE
I have problem using clip interogate

### ISSUE THREAD

**Issue by CryptoSoltan** [pharmapsychotic/clip-interrogator#8]
its keeps showing me this error
Traceback (most recent call last):
  File "C:\AI\stable-diffusion-webui\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 275, in run_predict
    output = await app.blocks.process_api(
  File "C:\AI\stable-diffusion-webui\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 787, in process_api
    result = await self.call_function(fn_index, inputs, iterator)
  File "C:\AI\stable-diffusion-webui\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 694, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\AI\stable-diffusion-webui\stable-diffusion-webui\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\AI\stable-diffusion-webui\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "C:\AI\stable-diffusion-webui\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "C:\AI\stable-diffusion-webui\stable-diffusion-webui\modules\ui.py", line 389, in interrogate
    prompt = shared.interrogator.interrogate(image)
  File "C:\AI\stable-diffusion-webui\stable-diffusion-webui\modules\interrogate.py", line 173, in interrogate
    res += "<error>"
TypeError: unsupported operand type(s) for +=: 'NoneType' and 'str'

**Comment by pharmapsychotic** [comment]
the version built into the web ui is very very old and not very good. you can use the latest version of CLIP Interrogator in Stable Diffusion Web UI with this extension https://github.com/pharmapsychotic/clip-interrogator-ext
