### ISSUE TITLE
bug 0.5.4

### ISSUE THREAD

**Issue by ucasiggcas** [pharmapsychotic/clip-interrogator#87]
Traceback (most recent call last):
  File "/bin/image2text.py", line 5, in <module>
    from clip_interrogator import Config, Interrogator, list_caption_models, list_clip_models
  File "/lib/python3.9/site-packages/clip_interrogator/__init__.py", line 1, in <module>
    from .clip_interrogator import Interrogator, Config
  File "python3.9/site-packages/clip_interrogator/clip_interrogator.py", line 30, in <module>
    class Config:
  File "/lib/python3.9/site-packages/clip_interrogator/clip_interrogator.py", line 53, in Config
    device: str = ("mps" if torch.backends.mps.is_available() else "cuda" if torch.cuda.is_available() else "cpu")
AttributeError: module 'torch.backends' has no attribute 'mps'

>>> import torch
>>> torch.__version__
'1.11.0'

**Comment by pharmapsychotic** [comment]
ah sorry looks like mps backend was added in pytorch 1.13
